[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Pretty paths to functions (query-string supported)
[[redirects]]
  from = "/proxy"
  to = "/.netlify/functions/proxy"
  status = 200

[[redirects]]
  from = "/m3u8"
  to = "/.netlify/functions/m3u8proxy"
  status = 200
