[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Map pretty paths to the functions AND forward the splat
[[redirects]]
  from = "/proxy/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/m3u8/*"
  to = "/.netlify/functions/m3u8proxy/:splat"
  status = 200
  force = true
